CREATE DATABASE AIRFLOW_DB;
CREATE SCHEMA CLEANSED_LAYER;
CREATE SCHEMA PRESENTATION_LAYER;

CREATE TABLE AIRFLOW_DB.CLEANSED_LAYER.SALES (
    ORDER_ID STRING,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    ORDER_DATE DATE,
    AMOUNT NUMERIC(10, 2),
    QUANTITY INT,
    DISCOUNT NUMERIC(10, 2),
    PROFIT NUMERIC(10, 2)
);
SELECT * FROM AIRFLOW_DB.CLEANSED_LAYER.SALES;

CREATE TABLE AIRFLOW_DB.CLEANSED_LAYER.CUSTOMERS(
    CUSTOMER_ID INT,
    NAME STRING, 
    EMAIL STRING,
    SIGNUP_DATE DATE
);

SELECT * FROM AIRFLOW_DB.CLEANSED_LAYER.CUSTOMERS;

CREATE TABLE AIRFLOW_DB.CLEANSED_LAYER.PRODUCTS(
    PRODUCT_ID INT,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMERIC(10,2)
);

SELECT * FROM AIRFLOW_DB.CLEANSED_LAYER.PRODUCTS;

CREATE TABLE AIRFLOW_DB.PRESENTATION_LAYER.MONTHLY_SALES_SUMMARY(
    ORDER_DATE DATE,
    UNIQUE_CUSTOMER INT,
    TOTAL_SALES NUMERIC(10, 2)
);

SELECT * FROM AIRFLOW_DB.PRESENTATION_LAYER.MONTHLY_SALES_SUMMARY;