
CREATE OR REPLACE STAGE SALES_ANALYTICS_DB.STAGING_LAYER.AWS_STAGE
    URL = 's3://etl-and-data-warehouse/Snowflake-advanced/'
    CREDENTIALS = (
        AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
        AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
    );

CREATE STAGE IF NOT EXISTS STAGING_LAYER.LOCAL_STAGE;
    
LIST @STAGING_LAYER.AWS_STAGE;

CREATE OR REPLACE FILE FORMAT STAGING_LAYER.CSV_FORMAT
    TYPE = CSV 
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

CREATE TABLE RAW_LAYER.SALES_ORDERS_RAW (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING, 
    ORDER_DATE STRING,
    AMOUNT STRING,
    PROFIT STRING,
    QUANTITY STRING,
    CATEGORY STRING,
    SUBCATEGORY STRING
);

COPY INTO RAW_LAYER.SALES_ORDERS_RAW
    FROM @STAGING_LAYER.AWS_STAGE
    FILE_FORMAT = STAGING_LAYER.CSV_FORMAT
    FILES = ('large_orders.csv')
    -- ON_ERROR = 'ABORT_STATEMENT'
    ON_ERROR = 'CONTINUE';

COPY INTO RAW_LAYER.SALES_ORDERS_RAW
    FROM @STAGING_LAYER.AWS_STAGE
    FILE_FORMAT = STAGING_LAYER.CSV_FORMAT
    PATTERN = ', *orders_.*\.csv' -- will load every file in the bucket that starts with the title orders_
    ON_ERROR = 'CONTINUE';

SELECT * FROM RAW_LAYER.SALES_ORDERS_RAW;  


CREATE OR REPLACE TRANSIENT TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    TO_DATE(ORDER_DATE, 'YYYY-MM-DD') AS ORDER_DATE,
    TRY_TO_DECIMAL(AMOUNT, 10, 2) AS AMOUNT,
    TRY_TO_DECIMAL(PROFIT, 10, 2) AS PROFIT,
    TRY_TO_NUMBER (QUANTITY) AS QUANTITY,
    INITCAP(CATEGORY) AS CATEGORY,
    INITCAP(SUBCATEGORY) AS SUBCATEGORY
FROM RAW_LAYER.SALES_ORDERS_RAW;

SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN;

CREATE MASKING POLICY IF NOT EXISTS CLEANSED_LAYER.MASKED_AMOUNT
    AS (VAL DECIMAL(10, 2))
    RETURNS DECIMAL(10, 2) ->
        CASE
            WHEN CURRENT_ROLE() = 'FINANCE_DEPARTMENT' THEN VAL
            ELSE -1
        END;

ALTER TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN
    MODIFY COLUMN AMOUNT
    SET MASKING POLICY CLEANSED_LAYER.MASKED_AMOUNT;

SHOW MASKING POLICIES;

SELECT * FROM TABLE(
    INFORMATION_SCHEMA.POLICY_REFERENCES(
        REF_ENTITY_NAME => 'CLEANSED_LAYER.SALES_ORDERS_CLEAN',
        REF_ENTITY_DOMAIN => 'TABLE'
    )
); 

DROP MASKING POLICY CLEANSED_LAYER.MASKED_AMOUNT;

CREATE MASKING POLICY CLEANSED_LAYER.MASKED_CATEGORY
    AS (VAL STRING)
    RETURNS STRING ->
        CASE
            WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN '******'
            ELSE VAL
        END;

ALTER TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN
MODIFY COLUMN CATEGORY
SET MASKING POLICY CLEANSED_LAYER.MASKED_CATEGORY;

SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN;

ALTER TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN
    MODIFY COLUMN CATEGORY
    UNSET MASKING POLICY;

SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN;

CREATE TRANSIENT TABLE CLEANSED_LAYER.SALES_ORDERS_MV_READY AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    ORDER_DATE,
    AMOUNT,
    PROFIT,
    QUANTITY,
    CATEGORY,
    SUBCATEGORY
FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN;

CREATE MATERIALIZED VIEW BUSINESS_LAYER.SALES_ORDERS_SUMMARY_MV AS
SELECT
    CATEGORY,
    SUM(AMOUNT) AS TOTAL_SALES
FROM CLEANSED_LAYER.SALES_ORDERS_MV_READY
GROUP BY CATEGORY;

SELECT * FROM BUSINESS_LAYER.SALES_ORDERS_SUMMARY_MV;

CREATE VIEW PRESENTATION_LAYER.TOTAL_SUMMARY AS
SELECT
    CATEGORY,
    TOTAL_SALES
FROM BUSINESS_LAYER.SALES_ORDERS_SUMMARY_MV
ORDER BY TOTAL_SALES DESC;

SELECT * FROM PRESENTATION_LAYER.TOTAL_SUMMARY;

CREATE TEMPORARY TABLE SALES_ORDERS_CLONE
    CLONE CLEANSED_LAYER.SALES_ORDERS_CLEAN;

SELECT * FROM SALES_ORDERS_CLONE;

CREATE OR REPLACE FILE FORMAT STAGING_LAYER.JSON_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE
  ENABLE_OCTAL      = FALSE;

CREATE OR REPLACE TABLE RAW_LAYER.REVIEWS_RAW(
    RAW_RECORD VARIANT 
);

COPY INTO RAW_LAYER.REVIEWS_RAW(RAW_RECORD)
  FROM @STAGING_LAYER.AWS_STAGE
  FILES = ('large_customer_reviews.json')
  FILE_FORMAT = STAGING_LAYER.JSON_FORMAT
  ON_ERROR    = 'CONTINUE';
SELECT * FROM RAW_LAYER.REVIEWS_RAW;

CREATE OR REPLACE TABLE CLEANSED_LAYER.REVIEWS AS
SELECT
  raw_record:"review_id"     ::INT     AS review_id,
  raw_record:"customer_id"   ::STRING  AS customer_id,
  raw_record:"review_data"."rating"   ::INT     AS rating,
  raw_record:"review_data"."comment"  ::STRING  AS comment,
  raw_record:"review_data"."verified" ::BOOLEAN AS verified
FROM RAW_LAYER.REVIEWS_RAW;

SELECT * FROM CLEANSED_LAYER.REVIEWS;

CREATE ROLE FURNITURE;

CREATE ROW ACCESS POLICY CLEANSED_LAYER.CATEGORY_FILTER
    AS (VAL STRING)
    RETURNS BOOLEAN ->
        CASE
            WHEN UPPER(TRIM(VAL)) = UPPER(CURRENT_ROLE()) THEN TRUE
            ELSE FALSE
        END;

ALTER TABLE CLEANSED_LAYER.SALES_ORDERS_CLEAN
ADD ROW ACCESS POLICY CLEANSED_LAYER.CATEGORY_FILTER
ON (CATEGORY);

SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN;

SELECT * FROM CLEANSED_LAYER.SALES_ORDERS_CLEAN AT (OFFSET => -1600); 

SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    ACTIVE_BYTES/1024/1024 AS SIZE_MD
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_SCHEMA IN ('RAW_LAYER', 'CLEANSED_LAYER', 'BUSINESS_LAYER')
ORDER BY SIZE_MD;

CREATE RESOURCE MONITOR TEAM_LIMIT
    WITH CREDIT_QUOTA = 50
    TRIGGERS ON 90 PERCENT DO SUSPEND;



