-- ELT process exercise: database, schemas, file format, raw tables, and data loading
-- Co-authored with CoCo
CREATE DATABASE SALES_DATABASE;

USE DATABASE SALES_DATABASE;

CREATE OR REPLACE STAGE SALES_DATABASE.STAGING_LAYER.AWS_STAGE
    URL = 's3://etl-and-data-warehouse/etl_and_elt/'
    CREDENTIALS = (
        AWS_KEY_ID = '<YOUR_AWS_KEY_ID>',
        AWS_SECRET_KEY = '<YOUR_AWS_SECRET_KEY>'
    );

LIST @SALES_DATABASE.STAGING_LAYER.AWS_STAGE;

CREATE SCHEMA SALES_DATABASE.STAGING_LAYER;
CREATE SCHEMA SALES_DATABASE.RAW_LAYER;
CREATE SCHEMA SALES_DATABASE.CLEANSED_LAYER;
CREATE SCHEMA SALES_DATABASE.ANALITYCS_LAYER;
CREATE SCHEMA SALES_DATABASE.PRESENTATION_LAYER;

CREATE FILE FORMAT SALES_DATABASE.STAGING_LAYER.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;


CREATE TABLE IF NOT EXISTS SALES_DATABASE.RAW_LAYER.RAW_SALES (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    ORDER_DATE STRING,
    AMOUNT STRING,
    QUANTITY STRING,
    DISCOUNT STRING,
    PROFIT STRING,
    SHIPPING_DAYS STRING
);

CREATE TABLE IF NOT EXISTS SALES_DATABASE.RAW_LAYER.RAW_PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE STRING
);

CREATE TABLE IF NOT EXISTS SALES_DATABASE.RAW_LAYER.RAW_CUSTOMERS (
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    SIGNUP_DATE STRING
);

COPY INTO SALES_DATABASE.RAW_LAYER.RAW_SALES
FROM @SALES_DATABASE.STAGING_LAYER.AWS_STAGE
FILE_FORMAT = SALES_DATABASE.STAGING_LAYER.CSV_FORMAT
FILES = ('sales_data.csv')
ON_ERROR = 'CONTINUE';

COPY INTO SALES_DATABASE.RAW_LAYER.RAW_PRODUCTS
FROM @SALES_DATABASE.STAGING_LAYER.AWS_STAGE
FILE_FORMAT = SALES_DATABASE.STAGING_LAYER.CSV_FORMAT
FILES = ('product_data.csv')
ON_ERROR = 'CONTINUE';

COPY INTO SALES_DATABASE.RAW_LAYER.RAW_CUSTOMERS
FROM @SALES_DATABASE.STAGING_LAYER.AWS_STAGE
FILE_FORMAT = SALES_DATABASE.STAGING_LAYER.CSV_FORMAT
FILES = ('customer_data.csv')
ON_ERROR = 'CONTINUE';

CREATE TRANSIENT TABLE SALES_DATABASE.CLEANSED_LAYER.CLEANSED_SALES AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    TRY_TO_DATE(ORDER_DATE, 'YYYY-MM-DD') AS ORDER_DATE,
    TO_DECIMAL(AMOUNT, 10, 2) AS AMOUNT,
    TRY_TO_NUMBER(QUANTITY) AS QUANTITY,
    PRODUCT_ID,
    TO_DECIMAL(DISCOUNT, 10, 2) AS DISCOUNT,
    TO_DECIMAL(PROFIT, 10, 2) AS PROFIT,
    COALESCE(TRY_TO_NUMBER(SHIPPING_DAYS), 0) AS SHIPPING_DAYS
FROM SALES_DATABASE.RAW_LAYER.RAW_SALES
WHERE TRY_TO_DATE(ORDER_DATE, 'YYYY-MM-DD') IS NOT NULL;

CREATE TRANSIENT TABLE SALES_DATABASE.CLEANSED_LAYER.CLEANSED_CUSTOMERS AS
SELECT
    CUSTOMER_ID STRING,
    LOWER(CUSTOMER_NAME) AS CUSTOMER_NAME,
    EMAIL,
    TO_DATE(SIGNUP_DATE, 'YYYY-MM-DD') AS SIGNUP_DATE
FROM SALES_DATABASE.RAW_LAYER.RAW_CUSTOMERS;


CREATE TRANSIENT TABLE SALES_DATABASE.CLEANSED_LAYER.CLEANSED_PRODUCTS AS
SELECT
    PRODUCT_ID,
    LOWER(PRODUCT_NAME) AS PRODUCT_NAME,
    LOWER(CATEGORY) AS CATEGORY,
    TO_DECIMAL(PRICE, 10, 2) AS PRICE  
FROM SALES_DATABASE.RAW_LAYER.RAW_PRODUCTS
WHERE PRICE > 0;

CREATE MATERIALIZED VIEW SALES_DATABASE.ANALITYCS_LAYER.MV_SALES_AGGREGATES AS
SELECT
    CUSTOMER_ID,
    DATE_TRUNC('month', ORDER_DATE) AS SALES_MONTH,
    COUNT (*) AS ORDER_COUNT,
    SUM(AMOUNT * QUANTITY) AS TOTAL_REVENUE
FROM SALES_DATABASE.CLEANSED_LAYER.CLEANSED_SALES
GROUP BY CUSTOMER_ID, DATE_TRUNC('month', ORDER_DATE);

CREATE MATERIALIZED VIEW SALES_DATABASE.ANALITYCS_LAYER.MV_CUSTOMER_SEGMENTS AS
SELECT
    CUSTOMER_ID,
    SUM(AMOUNT * QUANTITY) AS TOTAL_SPENT,
    CASE
        WHEN SUM(AMOUNT * QUANTITY) > 5000 THEN 'HIGH VALUE'
        WHEN SUM(AMOUNT * QUANTITY) BETWEEN 2500 AND 5000 THEN 'MEDIUM VALUE'
        ELSE 'LOW VALUE'
    END AS CUSTOMER_CATEGORY
FROM SALES_DATABASE.CLEANSED_LAYER.CLEANSED_SALES
GROUP BY CUSTOMER_ID;

CREATE VIEW SALES_DATABASE.PRESENTATION_LAYER.FINAL_SALES_REPORT AS 
SELECT
    S.SALES_MONTH,
    C.CUSTOMER_CATEGORY,
    SUM(S.TOTAL_REVENUE) AS TOTAL_SALES
FROM SALES_DATABASE.ANALITYCS_LAYER.MV_SALES_AGGREGATES AS S
JOIN SALES_DATABASE.ANALITYCS_LAYER.MV_CUSTOMER_SEGMENTS AS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    S.SALES_MONTH,
    C.CUSTOMER_CATEGORY
ORDER BY
    S.SALES_MONTH;

SELECT * FROM SALES_DATABASE.PRESENTATION_LAYER.FINAL_SALES_REPORT;