aws_conn_id: aws_conn_id

s3:
  bucket: etl-and-data-warehouse
  folder: apachi-airflow/

snowflake:
  conn_id: my_snowflake_conn
  database: AIRFLOW_DB
  targets:
    sales:
      schema: cleansed_layer
      table: sales 
    customers:
      schema: cleansed_layer
      table: customers
    products:
      schema: cleansed_layer
      table: products
    monthly_sales:
      schema: presentation_layer
      table: monthly_sales_summary